version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=5d41e4b69f9457f559a44254b58a812049ca66fb41090fd9364cff6d4c671f03
      - DJANGO_SETTINGS_MODULE=crypto_price_aggregator.settings  # Corrected setting
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "test"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
